// MedLink quiet-luxury SaaS system: warm canvas, black rail, soft pastel signals, calm operational motion.
import { useEffect, useState } from "react";
import {
  Activity, AlertCircle, ArrowLeft, Bell, Building2, ChevronRight, CircleHelp,
  ClipboardList, Database, Droplets, LayoutDashboard, LogOut, Menu, Package,
  Pencil, Plus, Search, Settings, ShieldCheck, SlidersHorizontal, Sparkles,
  Stethoscope, Syringe, X, Zap
} from "lucide-react";
import { toast } from "sonner";

const logo = "/assets/medlink-logo.svg";
const networkArt = "/assets/medlink-network.svg";
const opsArt = "/assets/medlink-operations.svg";
const authArt = "/assets/medlink-auth.svg";

type View = "dashboard" | "inventory" | "resource" | "add" | "organization" | "settings" | "login" | "onboarding";

type Resource = { name: string; category: string; quantity: string; unit: string; status: string; condition: string; expiry?: string; icon: any };
const resources: Resource[] = [
  { name: "Infusion Pump IP-400", category: "Equipment", quantity: "18", unit: "units", status: "AVAILABLE", condition: "Excellent", icon: Activity },
  { name: "Nitrile Examination Gloves", category: "Medical Supply", quantity: "2,840", unit: "pairs", status: "LOW STOCK", condition: "New", expiry: "Nov 2027", icon: Package },
  { name: "O-Negative Blood", category: "Blood", quantity: "12", unit: "units", status: "AVAILABLE", condition: "Cold chain", expiry: "Sep 14, 2026", icon: Droplets },
  { name: "Portable Oxygen Cylinder", category: "Equipment", quantity: "0", unit: "units", status: "OUT OF STOCK", condition: "—", icon: Stethoscope },
  { name: "Amoxicillin 500mg", category: "Medicine", quantity: "160", unit: "packs", status: "AVAILABLE", condition: "Sealed", expiry: "Mar 2028", icon: Syringe },
];

const nav = [
  { id: "dashboard", label: "Dashboard", icon: LayoutDashboard },
  { id: "organization", label: "Organization", icon: Building2 },
  { id: "inventory", label: "Inventory", icon: ClipboardList },
  { id: "resource", label: "Resources", icon: Database },
  { id: "settings", label: "Settings", icon: Settings },
] as const;

function StatusPill({ status }: { status: string }) {
  const styles: Record<string, string> = {
    AVAILABLE: "bg-[#e6f3eb] text-[#397154]",
    "LOW STOCK": "bg-[#fff0d9] text-[#956a2b]",
    "OUT OF STOCK": "bg-[#f3e8e9] text-[#98666b]",
    UNAVAILABLE: "bg-[#ececed] text-[#6d6d71]",
    VERIFIED: "bg-[#e6f3eb] text-[#397154]",
    PENDING: "bg-[#fff0d9] text-[#956a2b]",
  };
  return <span className={`status-pill ${styles[status] || "bg-[#ececed] text-[#666]"}`}><span className="status-dot" />{status}</span>;
}

function Sidebar({ view, setView, mobileOpen, setMobileOpen }: { view: View; setView: (v: View) => void; mobileOpen: boolean; setMobileOpen: (v: boolean) => void }) {
  return <>
    <aside className={`sidebar ${mobileOpen ? "mobile-open" : ""}`}>
      <div className="brand" onClick={() => { setView("dashboard"); setMobileOpen(false); }}>
        <div className="brand-mark"><img src={logo} alt="" /></div><span>MEDLINK</span>
      </div>
      <div className="workspace"><div className="workspace-avatar">AH</div><div><strong>Ardent Health</strong><small>Healthcare Network</small></div><ChevronRight size={15} /></div>
      <div className="nav-group"><small className="nav-caption">WORKSPACE</small>{nav.map(item => { const Icon = item.icon; return <button key={item.id} className={`nav-item ${view === item.id || (view === "add" && item.id === "inventory") ? "active" : ""}`} onClick={() => { setView(item.id); setMobileOpen(false); }}><Icon size={18} /><span>{item.label}</span>{item.id === "inventory" && <span className="nav-count">5</span>}</button> })}</div>
      <div className="rail-note"><Sparkles size={16} /><p><strong>Keep critical resources in view.</strong><br />Your inventory is in good standing.</p></div>
      <div className="sidebar-bottom"><button className="nav-item" onClick={() => toast.info("Help center is coming soon.")}><CircleHelp size={18} /><span>Help center</span></button><button className="nav-item" onClick={() => { setView("login"); setMobileOpen(false); }}><LogOut size={18} /><span>Log out</span></button><div className="rail-user"><div className="avatar">JD</div><div><strong>Jordan Davis</strong><small>Inventory admin</small></div><Settings size={15} /></div></div>
    </aside>
    {mobileOpen && <div className="mobile-scrim" onClick={() => setMobileOpen(false)} />}
  </>;
}

function Topbar({ title, setView, setMobileOpen }: { title: string; setView: (v: View) => void; setMobileOpen: (v: boolean) => void }) {
  return <header className="topbar"><div className="mobile-menu" onClick={() => window.dispatchEvent(new Event("medlink:open-nav"))}><Menu size={21} /></div><div><p className="eyebrow">ARDENT HEALTH NETWORK / 08:42 AM</p><h1>{title}</h1></div><div className="top-actions"><div className="searchbox"><Search size={17} /><input placeholder="Search resources" /></div><button className="icon-button" onClick={() => toast.info("You are all caught up.")}><Bell size={18} /><span className="notification-dot" /></button><button className="top-profile" onClick={() => setView("settings")}><div className="avatar">JD</div><span>Jordan Davis</span><ChevronRight size={15} /></button></div></header>;
}

function Metric({ label, value, note, tone, icon: Icon }: any) { return <div className={`metric-card ${tone}`}><div className="metric-top"><span>{label}</span><div className="metric-icon"><Icon size={17} /></div></div><div className="metric-value">{value}</div><div className="metric-note">{note}</div></div>; }

function Dashboard({ setView }: { setView: (v: View) => void }) {
  return <div className="page"><Topbar title="Good morning, Jordan" setView={setView} setMobileOpen={() => {}} /><main className="page-content"><div className="intro-row"><div><p className="section-kicker">TUESDAY, AUGUST 30, 2026</p><h2>Here’s your resource pulse.</h2><p className="muted">A clear view of what your teams have, need, and can act on next.</p></div><button className="button primary" onClick={() => setView("add")}><Plus size={17} /> Add resource</button></div><div className="metrics-grid"><Metric label="Total resources" value="128" note="Across 5 categories" tone="lilac" icon={Database} /><Metric label="Available" value="96" note="75% of inventory" tone="mint" icon={ShieldCheck} /><Metric label="Low stock" value="08" note="Needs attention" tone="peach" icon={AlertCircle} /><Metric label="Out of stock" value="02" note="Review this week" tone="blue" icon={Zap} /></div><div className="main-grid"><section className="card recent-card"><div className="card-heading"><div><p className="section-kicker">LIVE INVENTORY</p><h3>Recent resources</h3></div><button className="text-button" onClick={() => setView("inventory")}>View inventory <ChevronRight size={15} /></button></div><div className="resource-list">{resources.slice(0, 4).map((r, i) => <ResourceRow key={r.name} resource={r} onClick={() => setView("resource")} delay={i} />)}</div></section><section className="overview-card"><div className="overview-copy"><div><p className="section-kicker">ORGANIZATION OVERVIEW</p><h3>Connected, current,<br /><em>in control.</em></h3></div><span className="overview-badge"><Activity size={13} /> Syncing</span></div><div className="overview-art"><img src={networkArt} alt="Abstract connected healthcare network" /></div><div className="overview-foot"><div><strong>5</strong><span>active categories</span></div><div><strong>98.4%</strong><span>data completeness</span></div><button onClick={() => setView("organization")}>Organization profile <ChevronRight size={15} /></button></div></section></div><div className="bottom-grid"><section className="card status-card"><div className="card-heading"><div><p className="section-kicker">ORGANIZATION STATUS</p><h3>Verified organization</h3></div><StatusPill status="VERIFIED" /></div><p className="muted">Ardent Health Network is verified for biomedical resource management.</p><div className="progress-line"><span style={{ width: "100%" }} /></div><div className="status-meta"><span>Verification complete</span><span>100%</span></div></section><section className="card quick-card"><img src={opsArt} alt="Medical inventory supplies" /><div><p className="section-kicker">QUICK ACTION</p><h3>Keep your catalog current.</h3><button className="text-button" onClick={() => setView("add")}>Add a resource <ChevronRight size={15} /></button></div></section></div></main></div>;
}

function ResourceRow({ resource: r, onClick, delay = 0 }: { resource: Resource; onClick: () => void; delay?: number }) { const Icon = r.icon; return <button className="resource-row" style={{ animationDelay: `${delay * 40}ms` }} onClick={onClick}><div className="resource-icon"><Icon size={17} /></div><div className="resource-name"><strong>{r.name}</strong><span>{r.category}</span></div><div className="resource-qty"><strong>{r.quantity}</strong><span>{r.unit}</span></div><StatusPill status={r.status} /><ChevronRight size={16} className="row-arrow" /></button>; }

function Inventory({ setView }: { setView: (v: View) => void }) { const [filter, setFilter] = useState("All resources"); return <div className="page"><Topbar title="Biomedical inventory" setView={setView} setMobileOpen={() => {}} /><main className="page-content"><div className="intro-row"><div><p className="section-kicker">RESOURCE CATALOG / 128 ITEMS</p><h2>Everything in one view.</h2><p className="muted">Manage availability, condition, and expiry across your organization.</p></div><button className="button primary" onClick={() => setView("add")}><Plus size={17} /> Add resource</button></div><div className="inventory-toolbar"><div className="filter-chips">{["All resources", "Equipment", "Medicine", "Blood", "Medical Supply"].map(x => <button key={x} className={filter === x ? "selected" : ""} onClick={() => setFilter(x)}>{x}</button>)}</div><button className="filter-button" onClick={() => toast.info("More filters are coming soon.")}><SlidersHorizontal size={16} /> Filters</button></div><section className="card inventory-card"><div className="inventory-head"><span>Resource</span><span>Quantity</span><span>Status</span><span></span></div>{resources.filter(r => filter === "All resources" || r.category === filter).map((r, i) => <ResourceRow key={r.name} resource={r} onClick={() => setView("resource")} delay={i} />)}</section></main></div>; }

function ResourceDetail({ setView }: { setView: (v: View) => void }) { const r = resources[0]; return <div className="page"><Topbar title="Resource details" setView={setView} setMobileOpen={() => {}} /><main className="page-content detail-page"><button className="back-button" onClick={() => setView("inventory")}><ArrowLeft size={16} /> Back to inventory</button><div className="detail-heading"><div><div className="detail-icon"><Activity size={22} /></div><p className="section-kicker">EQUIPMENT / RESOURCE #ML-0041</p><h2>{r.name}</h2><p className="muted">Last updated today at 08:35 AM by Jordan Davis</p></div><div className="detail-actions"><StatusPill status="AVAILABLE" /><button className="button secondary" onClick={() => toast.success("Edit mode is ready in the full app.")}><Pencil size={16} /> Edit resource</button></div></div><div className="detail-stats"><div className="card detail-stat"><span>Quantity</span><strong>18</strong><small>units available</small></div><div className="card detail-stat"><span>Condition</span><strong>Excellent</strong><small>Last inspected Aug 12</small></div><div className="card detail-stat"><span>Active status</span><strong>Active</strong><small>Visible to organization</small></div><div className="card detail-stat"><span>Organization</span><strong>Ardent Health</strong><small>Healthcare Network</small></div></div><div className="detail-columns"><section className="card detail-description"><p className="section-kicker">DESCRIPTION</p><h3>Reliable infusion support for every ward.</h3><p className="muted">IP-400 programmable infusion pumps designed for controlled medication delivery. Each unit is maintained under Ardent Health Network’s biomedical equipment program.</p></section><section className="card detail-meta"><p className="section-kicker">RESOURCE METADATA</p><div><span>Created</span><strong>May 18, 2026</strong></div><div><span>Updated</span><strong>Aug 30, 2026</strong></div><div><span>Expiry</span><strong>Not applicable</strong></div></section></div></main></div>; }

function AddResource({ setView }: { setView: (v: View) => void }) { return <div className="page"><Topbar title="Add resource" setView={setView} setMobileOpen={() => {}} /><main className="page-content form-page"><button className="back-button" onClick={() => setView("inventory")}><ArrowLeft size={16} /> Back to inventory</button><div className="form-intro"><p className="section-kicker">NEW RESOURCE</p><h2>Add a resource to your catalog.</h2><p className="muted">Keep your team’s shared inventory accurate and ready to act on.</p></div><section className="card form-card"><div className="form-grid"><label>Resource name<input placeholder="e.g. Portable oxygen cylinder" /></label><label>Category<select defaultValue=""><option value="" disabled>Select category</option><option>Equipment</option><option>Medicine</option><option>Blood</option><option>Medical Supply</option></select></label><label className="wide">Description<textarea placeholder="Add a short description of this resource..." /></label><label>Quantity<input placeholder="0" type="number" /></label><label>Unit<select defaultValue=""><option value="" disabled>Select unit</option><option>Units</option><option>Packs</option><option>Pairs</option><option>Liters</option></select></label><label>Availability status<select defaultValue=""><option value="" disabled>Select status</option><option>AVAILABLE</option><option>LOW STOCK</option><option>UNAVAILABLE</option></select></label><label>Condition<select defaultValue=""><option value="" disabled>Select condition</option><option>New</option><option>Excellent</option><option>Good</option><option>Needs review</option></select></label><label>Expiry date<input type="date" /></label></div><div className="form-footer"><span className="muted"><ShieldCheck size={15} /> Changes are visible to verified members.</span><div><button className="button secondary" onClick={() => setView("inventory")}>Cancel</button><button className="button primary" onClick={() => { toast.success("Resource added to your catalog."); setView("inventory"); }}>Add resource <Plus size={16} /></button></div></div></section></main></div>; }

function Organization({ setView }: { setView: (v: View) => void }) { return <div className="page"><Topbar title="Organization" setView={setView} setMobileOpen={() => {}} /><main className="page-content"><div className="intro-row"><div><p className="section-kicker">ORGANIZATION PROFILE</p><h2>Ardent Health Network</h2><p className="muted">The verified identity behind your resource catalog.</p></div><button className="button secondary" onClick={() => toast.info("Organization editing is coming soon.")}><Pencil size={16} /> Edit profile</button></div><section className="org-hero card"><div className="org-symbol"><Building2 size={26} /></div><div><h3>Ardent Health Network</h3><p className="muted">Multi-specialty healthcare network · Bengaluru, Karnataka</p></div><StatusPill status="VERIFIED" /></section><div className="org-grid"><section className="card info-card"><p className="section-kicker">ORGANIZATION DETAILS</p>{[["Registration number","AHN-2024-0891"],["Organization type","Healthcare network"],["Email","operations@ardenthealth.org"],["Phone","+91 80 4567 8900"],["Address","14 Residency Road"],["City / State","Bengaluru, Karnataka 560025"]].map(([a,b]) => <div className="info-line" key={a}><span>{a}</span><strong>{b}</strong></div>)}</section><section className="card verification-card"><p className="section-kicker">VERIFICATION STATUS</p><div className="verify-ring"><ShieldCheck size={28} /></div><h3>Verified organization</h3><p className="muted">Your organization was verified on May 18, 2026. You can manage biomedical resources for your network.</p><button className="text-button" onClick={() => toast.info("Verification details are available to administrators.")}>View verification details <ChevronRight size={15} /></button></section></div></main></div>; }

function SettingsPage({ setView }: { setView: (v: View) => void }) { return <div className="page"><Topbar title="Settings" setView={setView} setMobileOpen={() => {}} /><main className="page-content"><div className="form-intro"><p className="section-kicker">ACCOUNT & PREFERENCES</p><h2>Settings</h2><p className="muted">Manage your profile and notification preferences.</p></div><div className="settings-grid"><section className="card settings-card"><p className="section-kicker">PROFILE INFORMATION</p><div className="profile-large"><div className="avatar avatar-lg">JD</div><div><h3>Jordan Davis</h3><p className="muted">Inventory admin</p></div><button className="button secondary small" onClick={() => toast.info("Profile editing is coming soon.")}>Edit</button></div>{[["Full name","Jordan Davis"],["Email","jordan.davis@ardenthealth.org"],["Role","Inventory administrator"]].map(([a,b]) => <div className="info-line" key={a}><span>{a}</span><strong>{b}</strong></div>)}</section><section className="card settings-card"><p className="section-kicker">ACCOUNT SETTINGS</p><div className="setting-row"><div><strong>Email notifications</strong><span>Receive updates about low stock</span></div><div className="toggle on"><span /></div></div><div className="setting-row"><div><strong>Weekly inventory digest</strong><span>A Monday summary for your network</span></div><div className="toggle on"><span /></div></div><div className="setting-row"><div><strong>Security alerts</strong><span>Important access and profile changes</span></div><div className="toggle on"><span /></div></div></section></div></main></div>; }

function Login({ setView }: { setView: (v: View) => void }) { return <div className="auth-page"><div className="auth-visual"><div className="auth-brand"><div className="brand-mark"><img src={logo} alt="" /></div><span>MEDLINK</span></div><div className="auth-art"><img src={authArt} alt="Connected medical cross illustration" /></div><div className="auth-quote"><p>“Clarity is care in motion.”</p><span>MedLink for verified healthcare organizations.</span></div></div><div className="auth-form"><div className="auth-form-inner"><p className="section-kicker">WELCOME BACK</p><h1>Sign in to MedLink.</h1><p className="muted">Manage what matters across your healthcare network.</p><label>Email address<input defaultValue="jordan.davis@ardenthealth.org" /></label><label>Password<input type="password" defaultValue="password" /></label><div className="form-inline"><label className="check"><input type="checkbox" defaultChecked /> Remember me</label><button className="text-button" onClick={() => toast.info("Password reset is coming soon.")}>Forgot password?</button></div><button className="button primary full" onClick={() => setView("dashboard")}>Sign in <ChevronRight size={17} /></button><p className="auth-switch">New to MedLink? <button onClick={() => setView("onboarding")}>Create an account</button></p></div></div></div>; }

function Onboarding({ setView }: { setView: (v: View) => void }) { return <div className="auth-page"><div className="auth-visual onboarding-visual"><div className="auth-brand"><div className="brand-mark"><img src={logo} alt="" /></div><span>MEDLINK</span></div><div className="onboarding-copy"><p className="section-kicker">STEP 02 / ORGANIZATION</p><h1>Bring your organization into view.</h1><p>Verified healthcare teams use MedLink to keep biomedical resources clear, current, and ready.</p><div className="onboarding-steps"><span className="done">01</span><span className="line" /><span className="current">02</span><span className="line" /><span>03</span></div></div></div><div className="auth-form"><div className="auth-form-inner"><p className="section-kicker">REGISTER ORGANIZATION</p><h1>Tell us about your team.</h1><p className="muted">We’ll review these details before activating your workspace.</p><div className="form-grid compact"><label className="wide">Organization name<input placeholder="e.g. Ardent Health Network" /></label><label>Registration number<input placeholder="Registration ID" /></label><label>Organization type<select defaultValue=""><option value="" disabled>Select type</option><option>Hospital</option><option>Healthcare network</option><option>Diagnostic center</option></select></label><label className="wide">Work email<input placeholder="operations@organization.org" /></label></div><button className="button primary full" onClick={() => { toast.success("Organization submitted for verification."); setView("dashboard"); }}>Submit for verification <ChevronRight size={17} /></button><p className="auth-switch">Already have an account? <button onClick={() => setView("login")}>Sign in</button></p></div></div></div>; }

export default function App() { const [view, setView] = useState<View>("dashboard"); const [mobileOpen, setMobileOpen] = useState(false); useEffect(() => { const openNav = () => setMobileOpen(true); window.addEventListener("medlink:open-nav", openNav); return () => window.removeEventListener("medlink:open-nav", openNav); }, []); const content = view === "dashboard" ? <Dashboard setView={setView} /> : view === "inventory" ? <Inventory setView={setView} /> : view === "resource" ? <ResourceDetail setView={setView} /> : view === "add" ? <AddResource setView={setView} /> : view === "organization" ? <Organization setView={setView} /> : view === "settings" ? <SettingsPage setView={setView} /> : view === "login" ? <Login setView={setView} /> : <Onboarding setView={setView} />; return view === "login" || view === "onboarding" ? content : <div className="app-shell"><Sidebar view={view} setView={setView} mobileOpen={mobileOpen} setMobileOpen={setMobileOpen} />{content}</div>; }
